### ISSUE TITLE
Peer dependency error

### ISSUE THREAD

**Issue by tacshooter** [bencevans/grunt-sequelize#20]
I keep getting this error when installing grunt-sequelize, but I've got sequelize 3.1 installed already. I've tried backing down my sequelize version to no avail, not that I should have to do that anyway... Has anyone else seen this? I've searched as well as I can and haven't been able to find anything. Any help sure would be appreciated. I'm on npm 2.10.1.

$ npm install grunt-sequelize
npm WARN peerDependencies The peer dependency sequelize@2.0.0-rc2 included from grunt-sequelize will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 3.14.13-c9
npm ERR! argv "node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "install" "grunt-sequelize"
npm ERR! node v0.10.35
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package sequelize does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-sequelize@3.0.0 wants sequelize@2.0.0-rc2

**Comment by maxmalov** [comment]
Yeah, I suppose this peerDependency entry should be removed. I'll try to fix this asap.

**Comment by maxmalov** [comment]
@tacshooter please checkout latest version from npm.

**Comment by bencevans** [comment]
Thanks Maxim!

**Comment by tacshooter** [comment]
Thanks Maxim!
